/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quizzes */
        get: operations["list_quizzes_api_quizzes_get"];
        put?: never;
        /** Create Quiz */
        post: operations["create_quiz_api_quizzes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{quiz_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quiz */
        get: operations["get_quiz_api_quizzes__quiz_id__get"];
        /** Update Quiz */
        put: operations["update_quiz_api_quizzes__quiz_id__put"];
        post?: never;
        /** Delete Quiz */
        delete: operations["delete_quiz_api_quizzes__quiz_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{quiz_id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder */
        put: operations["reorder_api_quizzes__quiz_id__order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{quiz_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Question */
        post: operations["add_question_api_quizzes__quiz_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Question */
        get: operations["get_question_api_questions__question_id__get"];
        /** Edit Question */
        put: operations["edit_question_api_questions__question_id__put"];
        post?: never;
        /** Delete Question */
        delete: operations["delete_question_api_questions__question_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Question */
        post: operations["duplicate_question_api_questions__question_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_questions__question_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/generate-outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Outputs */
        post: operations["generate_outputs_api_questions__question_id__generate_outputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/{quiz_id}/export.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Quiz */
        get: operations["export_quiz_api_quizzes__quiz_id__export_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quizzes/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Quiz */
        post: operations["import_quiz_api_quizzes_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve */
        get: operations["serve_api_media__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_games_get"];
        put?: never;
        /** Create Game */
        post: operations["create_game_api_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_games__game_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Next */
        post: operations["next__api_games__game_id__next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_api_games__game_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_games__game_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/adjust-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust Time */
        post: operations["adjust_time_api_games__game_id__adjust_time_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/end-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Now */
        post: operations["end_now_api_games__game_id__end_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Results */
        post: operations["results_api_games__game_id__results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leaderboard */
        post: operations["leaderboard_api_games__game_id__leaderboard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/podium": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Podium */
        post: operations["podium_api_games__game_id__podium_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/results/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override */
        post: operations["override_api_games__game_id__results_override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/questions/{question_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescore */
        post: operations["rescore_api_games__game_id__questions__question_id__rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/teams/{team_id}/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Points */
        post: operations["points_api_games__game_id__teams__team_id__points_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/score-events/{event_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo */
        post: operations["undo_api_games__game_id__score_events__event_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/kahoot-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kahoot */
        post: operations["kahoot_api_games__game_id__kahoot_scores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/teams/{team_id}/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kick */
        post: operations["kick_api_games__game_id__teams__team_id__kick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/teams/{team_id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rename */
        post: operations["rename_api_games__game_id__teams__team_id__rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/teams/{team_id}/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reissue */
        post: operations["reissue_api_games__game_id__teams__team_id__reissue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Settings */
        post: operations["settings_api_games__game_id__settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics */
        get: operations["get_analytics_api_games__game_id__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/analytics.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics Csv */
        get: operations["get_analytics_csv_api_games__game_id__analytics_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join */
        post: operations["join_api_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Me */
        get: operations["team_me_api_team_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Practice */
        get: operations["practice_api_practice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Submission */
        post: operations["create_submission_api_submissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_drafts__question_id__get"];
        /** Save Draft */
        put: operations["save_draft_api_drafts__question_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/_schemas/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ws Schema
         * @description Never called: exposes the WebSocket message shapes in OpenAPI for `npm run gen:types`.
         */
        get: operations["ws_schema_api__schemas_ws_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustTimeIn */
        AdjustTimeIn: {
            /** Delta S */
            delta_s?: number | null;
            /** Set Remaining S */
            set_remaining_s?: number | null;
        };
        /** AutoEnd */
        AutoEnd: {
            /**
             * All Passed
             * @default false
             */
            all_passed: boolean;
            /** After N Passed */
            after_n_passed?: number | null;
        };
        /** Benchmark */
        Benchmark: {
            /** Generator */
            generator: string;
            /**
             * Sizes
             * @default [
             *       500,
             *       2000,
             *       8000
             *     ]
             */
            sizes: number[];
            /**
             * Repeats
             * @default 3
             */
            repeats: number;
            /**
             * Cpu Limit S
             * @default 5
             */
            cpu_limit_s: number;
            /**
             * Floor Ms
             * @default 20
             */
            floor_ms: number;
        };
        /** BoardRow */
        BoardRow: {
            /** Team Id */
            team_id: string;
            /** Name */
            name: string;
            /** Points */
            points: number;
            /** Rank */
            rank: number;
            /** Prev Rank */
            prev_rank?: number | null;
            /**
             * Prev Points
             * @default 0
             */
            prev_points: number;
        };
        /** Body_import_quiz_api_quizzes_import_post */
        Body_import_quiz_api_quizzes_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_api_media_post */
        Body_upload_api_media_post: {
            /** File */
            file: string;
        };
        /** ChangePasswordIn */
        ChangePasswordIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** Closest */
        Closest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "closest";
            /**
             * Max
             * @default 4000
             */
            max: number;
            /**
             * Min Share
             * @default 0.5
             */
            min_share: number;
        };
        /** DraftIn */
        DraftIn: {
            /** Code */
            code: string;
        };
        /** ExpectIn */
        ExpectIn: {
            /** Expect State */
            expect_state?: string | null;
        };
        /** Flat */
        Flat: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "flat";
            /**
             * Max
             * @default 4000
             */
            max: number;
        };
        /** GameHeader */
        GameHeader: {
            /** Id */
            id: string;
            /**
             * State
             * @enum {string}
             */
            state: "lobby" | "round_intro" | "open" | "paused" | "closed" | "judging" | "results" | "leaderboard" | "podium" | "finished";
            /** Question Index */
            question_index: number;
            /** Question Count */
            question_count: number;
            /** Round Name */
            round_name: string | null;
            /** Question Type */
            question_type: ("super_fast" | "code_golf" | "best_complexity") | null;
            /** Deadline */
            deadline: string | null;
            /** Paused */
            paused: boolean;
            /** Remaining Ms */
            remaining_ms: number | null;
            /** Ending */
            ending: boolean;
            /** Ended Early */
            ended_early: boolean;
            /** Phase Ends At */
            phase_ends_at: string | null;
            /** Server Time */
            server_time: string;
            /** Judge Ok */
            judge_ok: boolean;
            /** Join Code */
            join_code?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IOCase */
        IOCase: {
            /**
             * Stdin
             * @default
             */
            stdin: string;
            /**
             * Expected
             * @default
             */
            expected: string;
        };
        /** JoinIn */
        JoinIn: {
            /** Code */
            code?: string | null;
            /** Team Name */
            team_name?: string | null;
            /** Rejoin Code */
            rejoin_code?: string | null;
        };
        /** KahootItem */
        KahootItem: {
            /** Team Id */
            team_id: string;
            /** Points */
            points: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Msg_judge_status */
        Msg_judge_status: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "judge.status";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** Msg_judging_progress */
        Msg_judging_progress: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "judging.progress";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: number;
            };
        };
        /** Msg_leaderboard_update */
        Msg_leaderboard_update: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "leaderboard.update";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: components["schemas"]["BoardRow"][];
            };
        };
        /** Msg_monitor_update */
        Msg_monitor_update: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "monitor.update";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** Msg_podium */
        Msg_podium: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "podium";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: components["schemas"]["BoardRow"][];
            };
        };
        /** Msg_points_adjusted */
        Msg_points_adjusted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "points.adjusted";
            /** Seq */
            seq: number;
            data: components["schemas"]["PointsAdjusted"];
        };
        /** Msg_pong */
        Msg_pong: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pong";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** Msg_presence */
        Msg_presence: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "presence";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: string[];
            };
        };
        /** Msg_progress_update */
        Msg_progress_update: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress.update";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** Msg_results */
        Msg_results: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "results";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** Msg_run_result */
        Msg_run_result: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.result";
            /** Seq */
            seq: number;
            data: components["schemas"]["RunResult"];
        };
        /** Msg_session_ended */
        Msg_session_ended: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.ended";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: string;
            };
        };
        /** Msg_session_replaced */
        Msg_session_replaced: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.replaced";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: string;
            };
        };
        /** Msg_snapshot */
        Msg_snapshot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "snapshot";
            /** Seq */
            seq: number;
            data: components["schemas"]["Snapshot"];
        };
        /** Msg_solve */
        Msg_solve: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "solve";
            /** Seq */
            seq: number;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** Msg_submission_result */
        Msg_submission_result: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "submission.result";
            /** Seq */
            seq: number;
            data: components["schemas"]["SubmissionResult"];
        };
        /** Msg_timer_update */
        Msg_timer_update: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "timer.update";
            /** Seq */
            seq: number;
            data: components["schemas"]["TimerUpdate"];
        };
        /** NewGameIn */
        NewGameIn: {
            /** Quiz Id */
            quiz_id: string;
        };
        /** OrderIn */
        OrderIn: {
            /** Question Ids */
            question_ids: string[];
        };
        /** OverrideIn */
        OverrideIn: {
            /** Team Id */
            team_id: string;
            /** Class Label */
            class_label?: string | null;
            /** Points */
            points?: number | null;
        };
        /** PointsAdjusted */
        PointsAdjusted: {
            /** Team Id */
            team_id: string;
            /** Team */
            team: string;
            /** Delta */
            delta: number;
            /** Note */
            note: string | null;
            /** Show Note */
            show_note: boolean;
            /** Total */
            total: number;
        };
        /** PointsIn */
        PointsIn: {
            /** Points */
            points: number;
            /** Note */
            note?: string | null;
        };
        /** QuestionConfig */
        QuestionConfig: {
            /** Examples */
            examples?: components["schemas"]["IOCase"][];
            /** Tests */
            tests?: components["schemas"]["IOCase"][];
            /**
             * Cpu Limit S
             * @default 2
             */
            cpu_limit_s: number;
            /**
             * Memory Mb
             * @default 128
             */
            memory_mb: number;
            /** Harness */
            harness?: string | null;
            benchmark?: components["schemas"]["Benchmark"] | null;
        };
        /**
         * QuestionIn
         * @description Body for creating or editing a coding question.
         */
        QuestionIn: {
            /** Round Name */
            round_name: string;
            type: components["schemas"]["QuestionType"];
            /** Title */
            title: string;
            /**
             * Description Md
             * @default
             */
            description_md: string;
            /** Image Media Id */
            image_media_id?: string | null;
            /** Image Alt */
            image_alt?: string | null;
            /**
             * Starter Code
             * @default
             */
            starter_code: string;
            /**
             * Reference Solution
             * @default
             */
            reference_solution: string;
            config?: components["schemas"]["QuestionConfig"];
            /**
             * Time Limit S
             * @default 240
             */
            time_limit_s: number;
            auto_end?: components["schemas"]["AutoEnd"];
            /** Scoring */
            scoring?: (components["schemas"]["SpeedWeighted"] | components["schemas"]["Closest"] | components["schemas"]["Flat"] | components["schemas"]["Ranked"]) | null;
            /** Expected Updated At */
            expected_updated_at?: string | null;
        };
        /**
         * QuestionType
         * @enum {string}
         */
        QuestionType: "super_fast" | "code_golf" | "best_complexity";
        /** QuizIn */
        QuizIn: {
            /** Title */
            title: string;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
        };
        /** Ranked */
        Ranked: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "ranked";
            /**
             * Points
             * @default [
             *       4000,
             *       3200,
             *       2400,
             *       1600
             *     ]
             */
            points: number[];
        };
        /** RenameIn */
        RenameIn: {
            /** Name */
            name: string;
        };
        /** RunCase */
        RunCase: {
            /** Index */
            index: number;
            /** Stdin */
            stdin: string | null;
            /** Stdout */
            stdout: string;
            /** Stderr */
            stderr: string;
            /** Status */
            status: string;
            /** Time Ms */
            time_ms: number | null;
            /** Memory Kb */
            memory_kb: number | null;
            /** Expected */
            expected?: string | null;
            /** Passed */
            passed?: boolean | null;
        };
        /** RunIn */
        RunIn: {
            /** Question Id */
            question_id: string;
            /** Code */
            code: string;
            /** Stdin */
            stdin?: string | null;
        };
        /** RunResult */
        RunResult: {
            /** Run Id */
            run_id: number;
            /** Custom */
            custom?: boolean | null;
            /** Cases */
            cases?: components["schemas"]["RunCase"][] | null;
            /** Error */
            error?: string | null;
        };
        /** SettingsIn */
        SettingsIn: {
            /** Allow Negative Totals */
            allow_negative_totals?: boolean | null;
            /** Show Reasons */
            show_reasons?: boolean | null;
            /** Sounds */
            sounds?: boolean | null;
        };
        /** Snapshot */
        Snapshot: {
            /**
             * Role
             * @enum {string}
             */
            role: "team" | "teacher" | "screen";
            game: components["schemas"]["GameHeader"];
            /** Leaderboard */
            leaderboard: components["schemas"]["BoardRow"][];
            /** Intro */
            intro?: {
                [key: string]: unknown;
            } | null;
            /** Question */
            question?: {
                [key: string]: unknown;
            } | null;
            /** Results */
            results?: {
                [key: string]: unknown;
            } | null;
            /** Podium */
            podium?: components["schemas"]["BoardRow"][] | null;
            /** Teams */
            teams?: {
                [key: string]: unknown;
            }[] | null;
            /** Progress */
            progress?: {
                [key: string]: unknown;
            } | null;
            /** Me */
            me?: {
                [key: string]: unknown;
            } | null;
            /** My Submissions */
            my_submissions?: {
                [key: string]: unknown;
            }[] | null;
            /** My Question Points */
            my_question_points?: number | null;
            /** Monitor */
            monitor?: {
                [key: string]: unknown;
            }[] | null;
            /** In Flight */
            in_flight?: number | null;
            /** Screen Token */
            screen_token?: string | null;
            /** Questions */
            questions?: {
                [key: string]: unknown;
            }[] | null;
            /** Kahoot Scores */
            kahoot_scores?: {
                [key: string]: number;
            } | null;
            /** Adjustments */
            adjustments?: {
                [key: string]: unknown;
            }[] | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /** All Teams */
            all_teams?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** SpeedWeighted */
        SpeedWeighted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "speed_weighted";
            /**
             * Max
             * @default 4000
             */
            max: number;
            /**
             * Speed Floor
             * @default 0.1
             */
            speed_floor: number;
            /**
             * Correctness Floor
             * @default 0.6
             */
            correctness_floor: number;
            /**
             * Min Pass
             * @default 0.5
             */
            min_pass: number;
        };
        /** StartIn */
        StartIn: {
            /** Expect State */
            expect_state?: string | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** SubmissionResult */
        SubmissionResult: {
            /** Id */
            id: number;
            /** Attempt */
            attempt: number;
            /** Status */
            status: string;
            /** Passed */
            passed: number | null;
            /** Total */
            total: number | null;
            /** Verdict */
            verdict: string | null;
            /** First Failed */
            first_failed: number | null;
            /** Error Summary */
            error_summary: string | null;
            /** Chars */
            chars: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Time Ms */
            time_ms: number | null;
            /** Points */
            points: number | null;
            /** Submitted At */
            submitted_at: string;
            /** Provisional */
            provisional?: boolean | null;
        };
        /** SubmitIn */
        SubmitIn: {
            /** Question Id */
            question_id: string;
            /** Code */
            code: string;
        };
        /** TimerUpdate */
        TimerUpdate: {
            /** Deadline */
            deadline: string | null;
            /** Paused */
            paused: boolean;
            /** Remaining Ms */
            remaining_ms: number | null;
            /** Ending */
            ending: boolean;
            /** Server Time */
            server_time: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    whoami_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quizzes_api_quizzes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_quiz_api_quizzes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_api_quizzes__quiz_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quiz_api_quizzes__quiz_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_quiz_api_quizzes__quiz_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_api_quizzes__quiz_id__order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_question_api_quizzes__quiz_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_question_api_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_question_api_questions__question_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_api_questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_question_api_questions__question_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_questions__question_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_outputs_api_questions__question_id__generate_outputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_quiz_api_quizzes__quiz_id__export_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quiz_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_quiz_api_quizzes_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_quiz_api_quizzes_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_media_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_api_media__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_games_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_game_api_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_games__game_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next__api_games__game_id__next_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_api_games__game_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_games__game_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_time_api_games__game_id__adjust_time_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustTimeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_now_api_games__game_id__end_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_api_games__game_id__results_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaderboard_api_games__game_id__leaderboard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    podium_api_games__game_id__podium_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_api_games__game_id__results_override_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescore_api_games__game_id__questions__question_id__rescore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    points_api_games__game_id__teams__team_id__points_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PointsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_api_games__game_id__score_events__event_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kahoot_api_games__game_id__kahoot_scores_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KahootItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kick_api_games__game_id__teams__team_id__kick_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_api_games__game_id__teams__team_id__rename_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reissue_api_games__game_id__teams__team_id__reissue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_api_games__game_id__settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_games__game_id__analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_csv_api_games__game_id__analytics_csv_get: {
        parameters: {
            query?: {
                kind?: string;
            };
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_api_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    team_me_api_team_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    practice_api_practice_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_submission_api_submissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_drafts__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_draft_api_drafts__question_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ws_schema_api__schemas_ws_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Msg_snapshot"] | components["schemas"]["Msg_submission_result"] | components["schemas"]["Msg_run_result"] | components["schemas"]["Msg_timer_update"] | components["schemas"]["Msg_points_adjusted"] | components["schemas"]["Msg_leaderboard_update"] | components["schemas"]["Msg_podium"] | components["schemas"]["Msg_results"] | components["schemas"]["Msg_monitor_update"] | components["schemas"]["Msg_progress_update"] | components["schemas"]["Msg_judging_progress"] | components["schemas"]["Msg_judge_status"] | components["schemas"]["Msg_presence"] | components["schemas"]["Msg_solve"] | components["schemas"]["Msg_pong"] | components["schemas"]["Msg_session_replaced"] | components["schemas"]["Msg_session_ended"];
                };
            };
        };
    };
}
